version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd eureka-server
      - mvn clean package
      - echo Building the docker image
      - docker build -t eureka-server.jar .
      - docker tag eureka-server.jar $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/kishore-ecr-repository:eureka-server
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/kishore-ecr-repository:eureka-server
      - echo Writing definition files
      - printf '[{"name":"eureka-server-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/kishore-ecr-repository:eureka-server > taskdefinition.json

artifacts:
  files: eureka-server/taskdefinition.json