version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd pensioner-detail-service
      - mvn clean package
      - echo Building the docker image
      - docker build -t pensioner-detail-service.jar .
      - docker tag pensioner-detail-service.jar $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/kishore-ecr-repository:pensioner-detail-service
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/kishore-ecr-repository:pensioner-detail-service
      - echo Writing definition files
      - printf '[{"name":"pensioner-detail-service-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/kishore-ecr-repository:pensioner-detail-service > taskdefinition.json

artifacts:
  files: pensioner-detail-service/taskdefinition.json